name = "cyber-pulse"
main = "src/worker.js"
compatibility_date = "2026-04-27"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "./public", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "cyberpulse"
database_id = "1609a7fa-1aae-4481-b843-427e370bb03e"

[triggers]
crons = ["*/30 * * * *"]
